### ISSUE TITLE
Browser platfrom isn't available on NPM

### ISSUE THREAD

**Issue by eAmin** [jichu4n/qbjc#11]
I've recently needed to use this cool library in my tiny project, when I try to import:

```import {BrowserExecutor} from 'qbjc/browser';```

when installing from NPM this module isn't present, but in the github source is available.

Would you please fix this issue?
Best regards.

**Comment by jichu4n** [comment]
Hi @eAmin and thanks for letting me know! I can indeed reproduce this when installing from NPM. It looks like a packaging issue. I'll work on a fix this in the next few days.

**Comment by jichu4n** [comment]
@eAmin OK I think it should be fixed now! Please try the latest version from NPM (`0.1.1`) and let me know!
